### ISSUE TITLE
Make clear that setting configuration is mandatory

### ISSUE THREAD

**Issue by kgjamieson** [kgjamieson/NEXT-psych#16]
You're allowed to make an experiment without putting in the access keys but it fails when you try to upload targets. Make it clear that you must set this data first

**Comment by kgjamieson** [comment]
And also, in this setting, when will the backend host not be the same as the machine?

**Comment by kgjamieson** [comment]
Aparantly even I do not know what the correct value for backend host should be, I put in the hostname (not including http:// or the port) and when I try to launch an experiment, I get an error. Looking at the logs I see

nextfrontenddocker_1 | [2015-10-29 23:32:01 +0000] [10] [DEBUG] GET /experiment/run_experiment/5632ac6d46e101000bd5701d
nextfrontenddocker_1 | [2015-10-29 23:32:01 +0000] [9] [DEBUG] POST /:8000/api/experiment
nextfrontenddocker_1 | Exception on /experiment/run_experiment/5632ac6d46e101000bd5701d [GET]
nextfrontenddocker_1 | Traceback (most recent call last):
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
nextfrontenddocker_1 |     response = self.full_dispatch_request()
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
nextfrontenddocker_1 |     rv = self.handle_user_exception(e)
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
nextfrontenddocker_1 |     reraise(exc_type, exc_value, tb)
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
nextfrontenddocker_1 |     rv = self.dispatch_request()
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
nextfrontenddocker_1 |     return self.view_functions[rule.endpoint](**req.view_args)
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 792, in decorated_view
nextfrontenddocker_1 |     return func(_args, *_kwargs)
nextfrontenddocker_1 |   File "/next_frontend/gui/base/current.py", line 82, in decorated_view
nextfrontenddocker_1 |     return func(_args, *_kwargs)
nextfrontenddocker_1 |   File "/next_frontend/gui/base/current.py", line 94, in decorated_view
nextfrontenddocker_1 |     return func(_args, *_kwargs)
nextfrontenddocker_1 |   File "/next_frontend/gui/base/controllers/experiment.py", line 129, in run_experiment
nextfrontenddocker_1 |     response_dict = app_resource.run_experiment(current_experiment)
nextfrontenddocker_1 |   File "/next_frontend/gui/base/app_manager/PoolBasedTripletMDS/PoolBasedTripletMDS.py", line 156, in run_experiment
nextfrontenddocker_1 |     response_dict = eval(response.text)
nextfrontenddocker_1 | Exception: invalid syntax (<string>, line 1). Error connecting to backend.

Which makes it clear that the hostname was not correctly set. Not sure why.
