### ISSUE TITLE
Fails to start new triplet experiment using AMI

### ISSUE THREAD

**Issue by kgjamieson** [kgjamieson/NEXT-psych#19]
I put in the keys, the next backup bucket (which my keys have access to), and hostname as ec2-52-32-131-67.us-west-2.compute.amazonaws.com.

I can successfully create a project, upload targets, and even get all the way to staging, but the experiment is stuck there. When I hit "Run Experiment" I get a "invalid syntax (<string>, line 1). Error connecting to backend." error. This is from the docker logs:

"""
nextfrontenddocker_1 | [2015-10-29 23:42:55 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:42:56 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:42:57 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:42:58 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:42:58 +0000] [11] [DEBUG] GET /new_project/
nextfrontenddocker_1 | [2015-10-29 23:42:59 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:43:00 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:43:00 +0000] [10] [DEBUG] GET /dashboard/
nextfrontenddocker_1 | [2015-10-29 23:43:01 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:43:02 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:43:02 +0000] [10] [DEBUG] GET /project/5632abfb46e101000ad6ec76
nextfrontenddocker_1 | [2015-10-29 23:43:03 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:43:04 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:43:04 +0000] [10] [DEBUG] GET /experiment/5632ac6d46e101000bd5701d
nextfrontenddocker_1 | Global Port 8000
nextfrontenddocker_1 | [2015-10-29 23:43:05 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:43:06 +0000] [1] [DEBUG] 5 workers
nextfrontenddocker_1 | [2015-10-29 23:43:06 +0000] [10] [DEBUG] GET /experiment/run_experiment/5632ac6d46e101000bd5701d
nextfrontenddocker_1 | [2015-10-29 23:43:06 +0000] [9] [DEBUG] POST /:8000/api/experiment
nextfrontenddocker_1 | Exception on /experiment/run_experiment/5632ac6d46e101000bd5701d [GET]
nextfrontenddocker_1 | Traceback (most recent call last):
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
nextfrontenddocker_1 |     response = self.full_dispatch_request()
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
nextfrontenddocker_1 |     rv = self.handle_user_exception(e)
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
nextfrontenddocker_1 |     reraise(exc_type, exc_value, tb)
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
nextfrontenddocker_1 |     rv = self.dispatch_request()
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
nextfrontenddocker_1 |     return self.view_functions[rule.endpoint](**req.view_args)
nextfrontenddocker_1 |   File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 792, in decorated_view
nextfrontenddocker_1 |     return func(_args, *_kwargs)
nextfrontenddocker_1 |   File "/next_frontend/gui/base/current.py", line 82, in decorated_view
nextfrontenddocker_1 |     return func(_args, *_kwargs)
nextfrontenddocker_1 |   File "/next_frontend/gui/base/current.py", line 94, in decorated_view
nextfrontenddocker_1 |     return func(_args, *_kwargs)
nextfrontenddocker_1 |   File "/next_frontend/gui/base/controllers/experiment.py", line 129, in run_experiment
nextfrontenddocker_1 |     response_dict = app_resource.run_experiment(current_experiment)
nextfrontenddocker_1 |   File "/next_frontend/gui/base/app_manager/PoolBasedTripletMDS/PoolBasedTripletMDS.py", line 156, in run_experiment
nextfrontenddocker_1 |     response_dict = eval(response.text)
nextfrontenddocker_1 | Exception: invalid syntax (<string>, line 1). Error connecting to backend.
"""

**Comment by kgjamieson** [comment]
Same problem for dueling
